name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0' 
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Install dotnet-format tool
        run: dotnet tool install --global dotnet-format
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: true

      - name: Format code
        run: dotnet format ./Project.sln --verify-no-changes

      - name: Run tests
        run: dotnet test ./Project.Tests/Project.Tests.csproj
