// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.DataAccess;

#nullable disable

namespace Project.DataAccess.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project.Entities.ContactPersonEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("ContactPersons");
                });

            modelBuilder.Entity("Project.Entities.MessageEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FromVolunteerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ToVolunteerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FromVolunteerId");

                    b.HasIndex("ToVolunteerId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Project.Entities.MilitaryUnitContactPersonEntity", b =>
                {
                    b.Property<int>("MilitaryUnitId")
                        .HasColumnType("int");

                    b.Property<int>("ContactPersonId")
                        .HasColumnType("int");

                    b.HasKey("MilitaryUnitId", "ContactPersonId");

                    b.HasIndex("ContactPersonId");

                    b.ToTable("MilitaryUnitContactPersons");
                });

            modelBuilder.Entity("Project.Entities.MilitaryUnitEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MilitaryUnits");
                });

            modelBuilder.Entity("Project.Entities.OrganizationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("nvarchar(18)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Project.Entities.RequestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompletedByVolunteerId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Importance")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("MilitaryUnitEntityId")
                        .HasColumnType("int");

                    b.Property<int>("MilitaryUnitId")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizationCompletedById")
                        .HasColumnType("int");

                    b.Property<int?>("OrganizationTakenById")
                        .HasColumnType("int");

                    b.Property<int?>("TakenByVolunteerId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CompletedByVolunteerId");

                    b.HasIndex("MilitaryUnitEntityId");

                    b.HasIndex("MilitaryUnitId");

                    b.HasIndex("OrganizationCompletedById");

                    b.HasIndex("OrganizationTakenById");

                    b.HasIndex("TakenByVolunteerId");

                    b.ToTable("Requests");
                });

            modelBuilder.Entity("Project.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Project.Entities.VolunteerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Volunteers");
                });

            modelBuilder.Entity("Project.Entities.VolunteerOrganizationEntity", b =>
                {
                    b.Property<int>("VolunteerId")
                        .HasColumnType("int");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("VolunteerId", "OrganizationId");

                    b.HasIndex("OrganizationId");

                    b.ToTable("VolunteerOrganizations");
                });

            modelBuilder.Entity("Project.Entities.MessageEntity", b =>
                {
                    b.HasOne("Project.Entities.VolunteerEntity", "FromVolunteer")
                        .WithMany("MessagesSent")
                        .HasForeignKey("FromVolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Entities.VolunteerEntity", "ToVolunteer")
                        .WithMany("MessagesReceived")
                        .HasForeignKey("ToVolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromVolunteer");

                    b.Navigation("ToVolunteer");
                });

            modelBuilder.Entity("Project.Entities.MilitaryUnitContactPersonEntity", b =>
                {
                    b.HasOne("Project.Entities.ContactPersonEntity", "ContactPerson")
                        .WithMany("MilitaryUnitContactPersons")
                        .HasForeignKey("ContactPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Entities.MilitaryUnitEntity", "MilitaryUnit")
                        .WithMany("MilitaryUnitContactPersons")
                        .HasForeignKey("MilitaryUnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContactPerson");

                    b.Navigation("MilitaryUnit");
                });

            modelBuilder.Entity("Project.Entities.RequestEntity", b =>
                {
                    b.HasOne("Project.Entities.VolunteerEntity", "CompletedByVolunteer")
                        .WithMany("CompletedRequests")
                        .HasForeignKey("CompletedByVolunteerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Project.Entities.MilitaryUnitEntity", null)
                        .WithMany("ActiveRequests")
                        .HasForeignKey("MilitaryUnitEntityId");

                    b.HasOne("Project.Entities.MilitaryUnitEntity", "MilitaryUnit")
                        .WithMany("Requests")
                        .HasForeignKey("MilitaryUnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Project.Entities.OrganizationEntity", "OrganizationCompletedBy")
                        .WithMany("CompletedRequests")
                        .HasForeignKey("OrganizationCompletedById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Project.Entities.OrganizationEntity", "OrganizationTakenBy")
                        .WithMany("ActiveRequests")
                        .HasForeignKey("OrganizationTakenById")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Project.Entities.VolunteerEntity", "TakenByVolunteer")
                        .WithMany("ActiveRequests")
                        .HasForeignKey("TakenByVolunteerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CompletedByVolunteer");

                    b.Navigation("MilitaryUnit");

                    b.Navigation("OrganizationCompletedBy");

                    b.Navigation("OrganizationTakenBy");

                    b.Navigation("TakenByVolunteer");
                });

            modelBuilder.Entity("Project.Entities.VolunteerOrganizationEntity", b =>
                {
                    b.HasOne("Project.Entities.OrganizationEntity", "Organization")
                        .WithMany("VolunteerOrganizations")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project.Entities.VolunteerEntity", "Volunteer")
                        .WithMany("VolunteerOrganizations")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("Project.Entities.ContactPersonEntity", b =>
                {
                    b.Navigation("MilitaryUnitContactPersons");
                });

            modelBuilder.Entity("Project.Entities.MilitaryUnitEntity", b =>
                {
                    b.Navigation("ActiveRequests");

                    b.Navigation("MilitaryUnitContactPersons");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Project.Entities.OrganizationEntity", b =>
                {
                    b.Navigation("ActiveRequests");

                    b.Navigation("CompletedRequests");

                    b.Navigation("VolunteerOrganizations");
                });

            modelBuilder.Entity("Project.Entities.VolunteerEntity", b =>
                {
                    b.Navigation("ActiveRequests");

                    b.Navigation("CompletedRequests");

                    b.Navigation("MessagesReceived");

                    b.Navigation("MessagesSent");

                    b.Navigation("VolunteerOrganizations");
                });
#pragma warning restore 612, 618
        }
    }
}
